### ISSUE TITLE
OpenFOAM configuration

### ISSUE THREAD

**Issue by nchristopher04** [kegiljarhus/shotshaper#2]
Hello,

First, I would like to thank you for sharing this, it is really well done and very useful!

I was wondering if you would be willing to share your OpenFOAM configuration/setup files? I would like to run some additional simulations on other discs, and it seems that you have fine tuned your meshing and simulation setup very well already.

Thanks!
Nick

**Comment by kegiljarhus** [comment]
Hi, thank you for the comments, happy that the software is useful for you. I have not published the OpenFOAM files as part of the repository, as it is difficult to make a generic setup that works for all discs. Also, from previous experience it often generates a lot of general OpenFOAM questions, which I unfortunately do not have the time to reply to. But if you send me an e-mail on knut.e.giljarhus@uis.no, I would be happy to share some pointers to get you started.
